image:
  repository: tccr.io/truecharts/plex
  pullPolicy: IfNotPresent
  tag: v1.32.0.6973@sha256:25f3e489457a7351bb25badba6b288b8c6b68c67ff973f6ff792010d7ecae110
service:
  main:
    ports:
      main:
        protocol: http
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"

plex:
  # User Defined
  serverIP: "127.0.0.1"
  additionalAdvertiseURL: ""
  disableGDM: true
  requireHTTPS: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              path: /identity
            readiness:
              enabled: true
              path: /identity
            startup:
              enabled: true
              path: /identity
          env:
            PLEX_PREFERENCE_GDM: 'GdmEnabled={{ ternary "0" "1" .Values.plex.disableGDM }}'
            # 0=Required, 1=Preferred
            PLEX_PREFERENCE_SEC_CON: 'secureConnections={{ ternary "0" "1" .Values.plex.requireHTTPS }}'
            # User Defined
            ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
            PLEX_CLAIM: ""

portal:
  open:
    enabled: true
