apiVersion: v2
appVersion: "25.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://deps.truecharts.org/
    version: 11.0.31
  - condition: collabora.enabled
    name: collabora-online
    repository: https://deps.truecharts.org/
    version: 14.0.18
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 5.0.33
deprecated: false
description: A private cloud server that puts the control and security of your own data back into your hands.
home: https://truecharts.org/charts/stable/nextcloud
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nextcloud.png
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: nextcloud
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/nextcloud
  - https://github.com/nextcloud/docker
  - https://github.com/nextcloud/helm
type: application
version: 19.0.51
annotations:
  truecharts.org/catagories: |
    - cloud
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
